[mgr]
prepend_keymap = [
  { on = "<Enter>", run = "plugin smart-enter" },
  { on = "<C-c>", run = "plugin system-clipboard" },
  { on = "<C-v>", run = "shell 'cb paste' --block", desc = "Paste from clipboard" },
  { on = "b", run = "plugin bunny" },
  { on = "T", run = "plugin toggle-pane max-preview" },
  { on = ["s", "s" ], run = "search --via=fd", desc = "Search" },
  { on = ["s", "d" ], run = "search --via=fd --args='-t d'", desc = "Search directories" },
  { on = ["s", "f" ], run = "search --via=fd --args='-t f'", desc = "Search files" },
  { on = ["u", "u"], run = "shell 'claude' --block", desc = "Claude code" },
  { on = ["u", "g"], run = "shell 'lazygit' --block", desc = "Lazygit" },
  { on = ["u", "c"], run = 'shell -- code "$@"', desc = "Open in VSCode" },
]
